#!/usr/bin/env python3
from pwn import *
import warnings
warnings.filterwarnings("ignore")
# exe = ELF("./juice.soe")
# context.log_level='debug'
# p = remote("addr", 1337)
# command = "php-bin/DEBUG/sbin/php-fpm -c php-bin/DEBUG/etc/php.ini --nodaemonize".split(" ")
command = "docker compose up --build".split(" ")
p = process(command)
# log.info(f"command {command}")

def gdbs():
    context.terminal = ["foot"]
    # gdb.attach(p, gdbscript="""
    #
    #            """)
    # p = gdb.debug(command,"""
    # target remote :6969
    #
    #                 """)
    return p

sla = lambda msg, data: p.sendlineafter(msg, data)
sa = lambda msg, data: p.sendafter(msg, data)
sl = lambda data: p.sendline(data)
s = lambda data: p.send(data)
# p = gdbs()









p.interactive()
# good luck pwning :)

