#!/usr/bin/env python3
from pwn import *
import warnings
warnings.filterwarnings("ignore")
import socket

exe = ELF("chate")
libc = ELF("./libc.so.6")
ld = ELF("ld.so.2")
# context.log_level='debug'
context.terminal = ["foot","tmux","new-session"]
# p = remote("addr", 1337)
p = process([exe.path])
def gdbs():
    clear = gdb.attach(p, gdbscript="""
    bb 0000000000001A07
    bb 0000000000001472

               """)
    # p = gdb.debug([exe.path],"""
    #
    #                 """)

sla = lambda msg, data: p.sendlineafter(msg, data)
sa = lambda msg, data: p.sendafter(msg, data)
sl = lambda data: p.sendline(data)
s = lambda data: p.send(data)

gdbs()

def create_client_socket(server_ip, server_port):
    client_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    server_address = (server_ip, server_port)
    client_socket.connect(server_address)
    try:
        message = '\0'
        client_socket.sendall(message.encode('utf-8'))
    
    finally:
        # Close the socket
        client_socket.close()
create_client_socket("127.0.0.1", 10000)






p.interactive()
# good luck pwning :)

