version: '3'
services:
  blind_firewall:
    build: .
    image: ctfae:blind_firewall
    ports:
      - 5000
    environment:
      FLAG: flag{hello_world}
      PORT: "5000"
    healthcheck:
      test: ["CMD-SHELL", "echo running > /dev/null"]
      interval: 5s
      timeout: 5s
      retries: 3
    cpus: 1
    mem_limit: 2G

