#!/usr/bin/env python3
from pwn import *
import warnings
warnings.filterwarnings("ignore")
exe = ELF("./maine")
libc = ELF("./libc.so.6")
ld = ELF("./ld-linux.so")
# context.log_level='debug'
# p = remote("addr", 1337)
p = process([exe.path])
def gdbs():
    context.terminal = ["foot"]
    gdb.attach(p, gdbscript="""

               """)
    # p = gdb.debug([exe.path],"""
    #
    #                 """)

sla = lambda msg, data: p.sendlineafter(msg, data)
sa = lambda msg, data: p.sendafter(msg, data)
sl = lambda data: p.sendline(data)
s = lambda data: p.send(data)
def add(idx,size):
    sl("1")
    sl(str(idx))
    sl(str(size))
def free(idx):
    sl("3")
    sl(str(idx))
    
gdbs()
for i in range(7):
    add(i,0x500)







p.interactive()
# good luck pwning :)

