#!/usr/bin/env python3
from pwn import *
import warnings
import os
warnings.filterwarnings("ignore")
exe = ELF("steghide_patched")
libc = ELF("./libc-2.31.so")
ld = ELF("./ld-2.31.so")
# context.log_level='debug'
# p = remote("addr", 1337)
stegfile_name = "lmao.bmp"
outfile_name = "hide.txt"
command = [exe.path, 'extract', '-sf', stegfile_name, '-p', "111111", '-xf', outfile_name]
def gdbs():
    # p = process(command)
    context.terminal = ["foot"]
    # gdb.attach(p, gdbscript="""
    #
    #            """)
    p = gdb.debug(command,"""

                    """)
    return p

sla = lambda msg, data: p.sendlineafter(msg, data)
sa = lambda msg, data: p.sendafter(msg, data)
sl = lambda data: p.sendline(data)
s = lambda data: p.send(data)
p = gdbs()








p.interactive()
# good luck pwning :)

